### ISSUE TITLE
add Database.Persist.*

### ISSUE THREAD

**Issue by goolord** [EdutainmentLIVE/prolude#12]
so far i want:
```haskell
Entity(entityKey,enittyVal,Entity), keyToOid, oidToKey
```

posting this for posterity/discussion

**Comment by goolord** [comment]
using the generated `FooId` types lets us use `keyToOid, oidToKey` instead of the monomorphic versions we were defining before. this eliminates a _ton_ of duplication in our code, I would heavily prefer using `Entity Foo` everywhere we need a `FooId` to what we're doing now

**Comment by goolord** [comment]
```haskell
episodeIdToText :: Types.EpisodeId -> Text
episodeIdToText = Gluon.objectIdToText . Types.episodeIdToObjectId

-->

keyToText :: ToBackendKey MongoContext record => Key record -> Text
keyToText = Gluon.objectIdToText . keyToOid

-- example: 
-- keyToText (foo :: Types.EpisodeId)
-- keyToText (foo :: Types.UserId)
-- keyToText (foo :: Types.CourseId)
```

**Comment by tfausak** [comment]
Would this be a problem with our custom `MongoId` type?

**Comment by aschmois** [comment]
Added in https://github.com/EdutainmentLIVE/prolude/pull/15
